### ISSUE TITLE
[Bug]: Square brackets in page title breaks parsing

### ISSUE THREAD

**Issue by rafaud** [chrisgrieser/alfred-read-later#4]
### Bug Description

Page with square brackets in title will add just fine. However later loading the list will break `select-read-later.js` script, causing reading list to not load, and not allowing for new items to be added.

### To Reproduce

Add any page with `[ ]` in the title. Example:

`- [ ] [Google [Example] ](https://www.google.com) 📆 2024-12-03`

### Debugging Log

```Text
[11:19:49.555] Read Later[Script Filter] Queuing argument '(null)'
[11:19:49.583] Read Later[Script Filter] Script with argv '(null)' finished
[11:19:49.590] ERROR: Read Later[Script Filter] Code 1: /Users/rafaud/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.58867FE7-E75A-48C4-B774-9CAF7C785AEC/scripts/select-read-later.js: execution error: Error: TypeError: undefined is not an object (evaluating 'str.replace') (-2700)
```

### Workflow Configuration

![5c961a5a58b75bac31aa1014232b18fa4a579575](https://github.com/user-attachments/assets/8e83ba0c-af03-4cec-8c4a-dcf555eab7e1)

### Checklist

- [X] I have [updated to the latest version](./releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
Good catch. I fixed it not in the selection script, but in the script adding new items, since it looks like `[]` in a markdown title makes those titles invalid markdown in general. 

<img alt="Showcase" width=70% src="https://github.com/user-attachments/assets/d09f153e-474d-4f00-bb2d-4b8e18687a13">

With the latest release, `[]` will thus be removed from any title when added. 

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/alfred-read-later/releases/download/1.4.4/alfred-read-later.alfredworkflow
